version: "3.8"

services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "DevPassword-2024-01-06"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
